from service.resolver_base import ResolverBase
from service.rule_item_mutex import RuleItemMutex


# DB 互斥规则已写入
class Resolver1923(ResolverBase):
    ANSWER_RANGE = ['1', '2', '3', '4', '5', '6', '7', '8', '9']

    def get_answer_range(self) -> []:
        return Resolver1923.ANSWER_RANGE

    def calculate_rules(self):
        super().calculate_rules()
        self.question_data.rules_list = [
            RuleItemMutex(self.question_data, '0,0;0,1;0,2;0,3;0,4;0,5;0,6;0,7;0,8'),
            RuleItemMutex(self.question_data, '1,0;1,1;1,2;1,3;1,4;1,5;1,6;1,7;1,8'),
            RuleItemMutex(self.question_data, '2,0;2,1;2,2;2,3;2,4;2,5;2,6;2,7;2,8'),
            RuleItemMutex(self.question_data, '3,0;3,1;3,2;3,3;3,4;3,5;3,6;3,7;3,8'),
            RuleItemMutex(self.question_data, '4,0;4,1;4,2;4,3;4,4;4,5;4,6;4,7;4,8'),
            RuleItemMutex(self.question_data, '5,0;5,1;5,2;5,3;5,4;5,5;5,6;5,7;5,8'),
            RuleItemMutex(self.question_data, '6,0;6,1;6,2;6,3;6,4;6,5;6,6;6,7;6,8'),
            RuleItemMutex(self.question_data, '7,0;7,1;7,2;7,3;7,4;7,5;7,6;7,7;7,8'),
            RuleItemMutex(self.question_data, '8,0;8,1;8,2;8,3;8,4;8,5;8,6;8,7;8,8'),

            RuleItemMutex(self.question_data, '0,0;1,0;2,0;3,0;4,0;5,0;6,0;7,0;8,0'),
            RuleItemMutex(self.question_data, '0,1;1,1;2,1;3,1;4,1;5,1;6,1;7,1;8,1'),
            RuleItemMutex(self.question_data, '0,2;1,2;2,2;3,2;4,2;5,2;6,2;7,2;8,2'),
            RuleItemMutex(self.question_data, '0,3;1,3;2,3;3,3;4,3;5,3;6,3;7,3;8,3'),
            RuleItemMutex(self.question_data, '0,4;1,4;2,4;3,4;4,4;5,4;6,4;7,4;8,4'),
            RuleItemMutex(self.question_data, '0,5;1,5;2,5;3,5;4,5;5,5;6,5;7,5;8,5'),
            RuleItemMutex(self.question_data, '0,6;1,6;2,6;3,6;4,6;5,6;6,6;7,6;8,6'),
            RuleItemMutex(self.question_data, '0,7;1,7;2,7;3,7;4,7;5,7;6,7;7,7;8,7'),
            RuleItemMutex(self.question_data, '0,8;1,8;2,8;3,8;4,8;5,8;6,8;7,8;8,8'),

            RuleItemMutex(self.question_data, '0,0;0,1;0,2;1,0;1,1;1,2;2,0;2,1;2,2'),
            RuleItemMutex(self.question_data, '3,0;3,1;3,2;4,0;4,1;4,2;5,0;5,1;5,2'),
            RuleItemMutex(self.question_data, '6,0;6,1;6,2;7,0;7,1;7,2;8,0;8,1;8,2'),
            RuleItemMutex(self.question_data, '0,3;0,4;0,5;1,3;1,4;1,5;2,3;2,4;2,5'),
            RuleItemMutex(self.question_data, '3,3;3,4;3,5;4,3;4,4;4,5;5,3;5,4;5,5'),
            RuleItemMutex(self.question_data, '6,3;6,4;6,5;7,3;7,4;7,5;8,3;8,4;8,5'),
            RuleItemMutex(self.question_data, '0,6;0,7;0,8;1,6;1,7;1,8;2,6;2,7;2,8'),
            RuleItemMutex(self.question_data, '3,6;3,7;3,8;4,6;4,7;4,8;5,6;5,7;5,8'),
            RuleItemMutex(self.question_data, '6,6;6,7;6,8;7,6;7,7;7,8;8,6;8,7;8,8'),

            # 1
            RuleItemMutex(self.question_data, '0,0;1,2'),
            RuleItemMutex(self.question_data, '0,1;1,3'),
            RuleItemMutex(self.question_data, '0,2;1,4'),
            RuleItemMutex(self.question_data, '0,3;1,5'),
            RuleItemMutex(self.question_data, '0,4;1,6'),
            RuleItemMutex(self.question_data, '0,5;1,7'),
            RuleItemMutex(self.question_data, '0,6;1,8'),

            RuleItemMutex(self.question_data, '1,0;2,2'),
            RuleItemMutex(self.question_data, '1,1;2,3'),
            RuleItemMutex(self.question_data, '1,2;2,4'),
            RuleItemMutex(self.question_data, '1,3;2,5'),
            RuleItemMutex(self.question_data, '1,4;2,6'),
            RuleItemMutex(self.question_data, '1,5;2,7'),
            RuleItemMutex(self.question_data, '1,6;2,8'),

            RuleItemMutex(self.question_data, '2,0;3,2'),
            RuleItemMutex(self.question_data, '2,1;3,3'),
            RuleItemMutex(self.question_data, '2,2;3,4'),
            RuleItemMutex(self.question_data, '2,3;3,5'),
            RuleItemMutex(self.question_data, '2,4;3,6'),
            RuleItemMutex(self.question_data, '2,5;3,7'),
            RuleItemMutex(self.question_data, '2,6;3,8'),

            RuleItemMutex(self.question_data, '3,0;4,2'),
            RuleItemMutex(self.question_data, '3,1;4,3'),
            RuleItemMutex(self.question_data, '3,2;4,4'),
            RuleItemMutex(self.question_data, '3,3;4,5'),
            RuleItemMutex(self.question_data, '3,4;4,6'),
            RuleItemMutex(self.question_data, '3,5;4,7'),
            RuleItemMutex(self.question_data, '3,6;4,8'),

            RuleItemMutex(self.question_data, '4,0;5,2'),
            RuleItemMutex(self.question_data, '4,1;5,3'),
            RuleItemMutex(self.question_data, '4,2;5,4'),
            RuleItemMutex(self.question_data, '4,3;5,5'),
            RuleItemMutex(self.question_data, '4,4;5,6'),
            RuleItemMutex(self.question_data, '4,5;5,7'),
            RuleItemMutex(self.question_data, '4,6;5,8'),

            RuleItemMutex(self.question_data, '5,0;6,2'),
            RuleItemMutex(self.question_data, '5,1;6,3'),
            RuleItemMutex(self.question_data, '5,2;6,4'),
            RuleItemMutex(self.question_data, '5,3;6,5'),
            RuleItemMutex(self.question_data, '5,4;6,6'),
            RuleItemMutex(self.question_data, '5,5;6,7'),
            RuleItemMutex(self.question_data, '5,6;6,8'),

            RuleItemMutex(self.question_data, '6,0;7,2'),
            RuleItemMutex(self.question_data, '6,1;7,3'),
            RuleItemMutex(self.question_data, '6,2;7,4'),
            RuleItemMutex(self.question_data, '6,3;7,5'),
            RuleItemMutex(self.question_data, '6,4;7,6'),
            RuleItemMutex(self.question_data, '6,5;7,7'),
            RuleItemMutex(self.question_data, '6,6;7,8'),

            RuleItemMutex(self.question_data, '7,0;8,2'),
            RuleItemMutex(self.question_data, '7,1;8,3'),
            RuleItemMutex(self.question_data, '7,2;8,4'),
            RuleItemMutex(self.question_data, '7,3;8,5'),
            RuleItemMutex(self.question_data, '7,4;8,6'),
            RuleItemMutex(self.question_data, '7,5;8,7'),
            RuleItemMutex(self.question_data, '7,6;8,8'),

            RuleItemMutex(self.question_data, '0,0;2,1'),
            RuleItemMutex(self.question_data, '1,0;3,1'),
            RuleItemMutex(self.question_data, '2,0;4,1'),
            RuleItemMutex(self.question_data, '3,0;5,1'),
            RuleItemMutex(self.question_data, '4,0;6,1'),
            RuleItemMutex(self.question_data, '5,0;7,1'),
            RuleItemMutex(self.question_data, '6,0;8,1'),

            # 2
            RuleItemMutex(self.question_data, '0,1;2,2'),
            RuleItemMutex(self.question_data, '1,1;3,2'),
            RuleItemMutex(self.question_data, '2,1;4,2'),
            RuleItemMutex(self.question_data, '3,1;5,2'),
            RuleItemMutex(self.question_data, '4,1;6,2'),
            RuleItemMutex(self.question_data, '5,1;7,2'),
            RuleItemMutex(self.question_data, '6,1;8,2'),

            RuleItemMutex(self.question_data, '0,2;2,3'),
            RuleItemMutex(self.question_data, '1,2;3,3'),
            RuleItemMutex(self.question_data, '2,2;4,3'),
            RuleItemMutex(self.question_data, '3,2;5,3'),
            RuleItemMutex(self.question_data, '4,2;6,3'),
            RuleItemMutex(self.question_data, '5,2;7,3'),
            RuleItemMutex(self.question_data, '6,2;8,3'),

            RuleItemMutex(self.question_data, '0,3;2,4'),
            RuleItemMutex(self.question_data, '1,3;3,4'),
            RuleItemMutex(self.question_data, '2,3;4,4'),
            RuleItemMutex(self.question_data, '3,3;5,4'),
            RuleItemMutex(self.question_data, '4,3;6,4'),
            RuleItemMutex(self.question_data, '5,3;7,4'),
            RuleItemMutex(self.question_data, '6,3;8,4'),

            RuleItemMutex(self.question_data, '0,4;2,5'),
            RuleItemMutex(self.question_data, '1,4;3,5'),
            RuleItemMutex(self.question_data, '2,4;4,5'),
            RuleItemMutex(self.question_data, '3,4;5,5'),
            RuleItemMutex(self.question_data, '4,4;6,5'),
            RuleItemMutex(self.question_data, '5,4;7,5'),
            RuleItemMutex(self.question_data, '6,4;8,5'),

            RuleItemMutex(self.question_data, '0,5;2,6'),
            RuleItemMutex(self.question_data, '1,5;3,6'),
            RuleItemMutex(self.question_data, '2,5;4,6'),
            RuleItemMutex(self.question_data, '3,5;5,6'),
            RuleItemMutex(self.question_data, '4,5;6,6'),
            RuleItemMutex(self.question_data, '5,5;7,6'),
            RuleItemMutex(self.question_data, '6,5;8,6'),

            RuleItemMutex(self.question_data, '0,6;2,7'),
            RuleItemMutex(self.question_data, '1,6;3,7'),
            RuleItemMutex(self.question_data, '2,6;4,7'),
            RuleItemMutex(self.question_data, '3,6;5,7'),
            RuleItemMutex(self.question_data, '4,6;6,7'),
            RuleItemMutex(self.question_data, '5,6;7,7'),
            RuleItemMutex(self.question_data, '6,6;8,7'),

            RuleItemMutex(self.question_data, '0,7;2,8'),
            RuleItemMutex(self.question_data, '1,7;3,8'),
            RuleItemMutex(self.question_data, '2,7;4,8'),
            RuleItemMutex(self.question_data, '3,7;5,8'),
            RuleItemMutex(self.question_data, '4,7;6,8'),
            RuleItemMutex(self.question_data, '5,7;7,8'),
            RuleItemMutex(self.question_data, '6,7;8,8'),

            # 3
            RuleItemMutex(self.question_data, '0,1;2,0'),
            RuleItemMutex(self.question_data, '1,1;3,0'),
            RuleItemMutex(self.question_data, '2,1;4,0'),
            RuleItemMutex(self.question_data, '3,1;5,0'),
            RuleItemMutex(self.question_data, '4,1;6,0'),
            RuleItemMutex(self.question_data, '5,1;7,0'),
            RuleItemMutex(self.question_data, '6,1;8,0'),

            RuleItemMutex(self.question_data, '0,2;2,1'),
            RuleItemMutex(self.question_data, '1,2;3,1'),
            RuleItemMutex(self.question_data, '2,2;4,1'),
            RuleItemMutex(self.question_data, '3,2;5,1'),
            RuleItemMutex(self.question_data, '4,2;6,1'),
            RuleItemMutex(self.question_data, '5,2;7,1'),
            RuleItemMutex(self.question_data, '6,2;8,1'),

            RuleItemMutex(self.question_data, '0,3;2,2'),
            RuleItemMutex(self.question_data, '1,3;3,2'),
            RuleItemMutex(self.question_data, '2,3;4,2'),
            RuleItemMutex(self.question_data, '3,3;5,2'),
            RuleItemMutex(self.question_data, '4,3;6,2'),
            RuleItemMutex(self.question_data, '5,3;7,2'),
            RuleItemMutex(self.question_data, '6,3;8,2'),

            RuleItemMutex(self.question_data, '0,4;2,3'),
            RuleItemMutex(self.question_data, '1,4;3,3'),
            RuleItemMutex(self.question_data, '2,4;4,3'),
            RuleItemMutex(self.question_data, '3,4;5,3'),
            RuleItemMutex(self.question_data, '4,4;6,3'),
            RuleItemMutex(self.question_data, '5,4;7,3'),
            RuleItemMutex(self.question_data, '6,4;8,3'),

            RuleItemMutex(self.question_data, '0,5;2,4'),
            RuleItemMutex(self.question_data, '1,5;3,4'),
            RuleItemMutex(self.question_data, '2,5;4,4'),
            RuleItemMutex(self.question_data, '3,5;5,4'),
            RuleItemMutex(self.question_data, '4,5;6,4'),
            RuleItemMutex(self.question_data, '5,5;7,4'),
            RuleItemMutex(self.question_data, '6,5;8,4'),

            RuleItemMutex(self.question_data, '0,6;2,5'),
            RuleItemMutex(self.question_data, '1,6;3,5'),
            RuleItemMutex(self.question_data, '2,6;4,5'),
            RuleItemMutex(self.question_data, '3,6;5,5'),
            RuleItemMutex(self.question_data, '4,6;6,5'),
            RuleItemMutex(self.question_data, '5,6;7,5'),
            RuleItemMutex(self.question_data, '6,6;8,5'),

            RuleItemMutex(self.question_data, '0,7;2,6'),
            RuleItemMutex(self.question_data, '1,7;3,6'),
            RuleItemMutex(self.question_data, '2,7;4,6'),
            RuleItemMutex(self.question_data, '3,7;5,6'),
            RuleItemMutex(self.question_data, '4,7;6,6'),
            RuleItemMutex(self.question_data, '5,7;7,6'),
            RuleItemMutex(self.question_data, '6,7;8,6'),

            RuleItemMutex(self.question_data, '0,8;2,7'),
            RuleItemMutex(self.question_data, '1,8;3,7'),
            RuleItemMutex(self.question_data, '2,8;4,7'),
            RuleItemMutex(self.question_data, '3,8;5,7'),
            RuleItemMutex(self.question_data, '4,8;6,7'),
            RuleItemMutex(self.question_data, '5,8;7,7'),
            RuleItemMutex(self.question_data, '6,8;8,7'),

            # 4
            RuleItemMutex(self.question_data, '0,2;1,0'),
            RuleItemMutex(self.question_data, '1,2;2,0'),
            RuleItemMutex(self.question_data, '2,2;3,0'),
            RuleItemMutex(self.question_data, '3,2;4,0'),
            RuleItemMutex(self.question_data, '4,2;5,0'),
            RuleItemMutex(self.question_data, '5,2;6,0'),
            RuleItemMutex(self.question_data, '6,2;7,0'),
            RuleItemMutex(self.question_data, '7,2;8,0'),

            RuleItemMutex(self.question_data, '0,3;1,1'),
            RuleItemMutex(self.question_data, '1,3;2,1'),
            RuleItemMutex(self.question_data, '2,3;3,1'),
            RuleItemMutex(self.question_data, '3,3;4,1'),
            RuleItemMutex(self.question_data, '4,3;5,1'),
            RuleItemMutex(self.question_data, '5,3;6,1'),
            RuleItemMutex(self.question_data, '6,3;7,1'),
            RuleItemMutex(self.question_data, '7,3;8,1'),

            RuleItemMutex(self.question_data, '0,4;1,2'),
            RuleItemMutex(self.question_data, '1,4;2,2'),
            RuleItemMutex(self.question_data, '2,4;3,2'),
            RuleItemMutex(self.question_data, '3,4;4,2'),
            RuleItemMutex(self.question_data, '4,4;5,2'),
            RuleItemMutex(self.question_data, '5,4;6,2'),
            RuleItemMutex(self.question_data, '6,4;7,2'),
            RuleItemMutex(self.question_data, '7,4;8,2'),

            RuleItemMutex(self.question_data, '0,5;1,3'),
            RuleItemMutex(self.question_data, '1,5;2,3'),
            RuleItemMutex(self.question_data, '2,5;3,3'),
            RuleItemMutex(self.question_data, '3,5;4,3'),
            RuleItemMutex(self.question_data, '4,5;5,3'),
            RuleItemMutex(self.question_data, '5,5;6,3'),
            RuleItemMutex(self.question_data, '6,5;7,3'),
            RuleItemMutex(self.question_data, '7,5;8,3'),

            RuleItemMutex(self.question_data, '0,6;1,4'),
            RuleItemMutex(self.question_data, '1,6;2,4'),
            RuleItemMutex(self.question_data, '2,6;3,4'),
            RuleItemMutex(self.question_data, '3,6;4,4'),
            RuleItemMutex(self.question_data, '4,6;5,4'),
            RuleItemMutex(self.question_data, '5,6;6,4'),
            RuleItemMutex(self.question_data, '6,6;7,4'),
            RuleItemMutex(self.question_data, '7,6;8,4'),

            RuleItemMutex(self.question_data, '0,7;1,5'),
            RuleItemMutex(self.question_data, '1,7;2,5'),
            RuleItemMutex(self.question_data, '2,7;3,5'),
            RuleItemMutex(self.question_data, '3,7;4,5'),
            RuleItemMutex(self.question_data, '4,7;5,5'),
            RuleItemMutex(self.question_data, '5,7;6,5'),
            RuleItemMutex(self.question_data, '6,7;7,5'),
            RuleItemMutex(self.question_data, '7,7;8,5'),

            RuleItemMutex(self.question_data, '0,8;1,6'),
            RuleItemMutex(self.question_data, '1,8;2,6'),
            RuleItemMutex(self.question_data, '2,8;3,6'),
            RuleItemMutex(self.question_data, '3,8;4,6'),
            RuleItemMutex(self.question_data, '4,8;5,6'),
            RuleItemMutex(self.question_data, '5,8;6,6'),
            RuleItemMutex(self.question_data, '6,8;7,6'),
            RuleItemMutex(self.question_data, '7,8;8,6'),

        ]

    def calculate_editable_original_data(self):
        super().calculate_editable_original_data()
        for y_index in range(len(self.question_data.editable_original_data)):
            for x_index in range(len(self.question_data.editable_original_data[y_index])):
                if self.question_data.editable_original_data[y_index][x_index] == '':
                    self.question_data.editable_original_data[y_index][x_index] = '#'
